feature/pinterest-keywords-variable-addition
fivetran/dbt_ad_reporting pull request #89
Opened 2023-06-06 22:05 UTC by fivetran-joemarkiewicz

## PR Overview
**This PR will address the following Issue/Feature:** #77 

**This PR will result in the following new package version:** `v1.4.0`

While this isn't technically breaking, it will be included in the next major release. As such we will mark it as breaking.

**Please detail what change(s) this PR introduces and any additional information that should be known during the review of this PR:**

This PR includes a new variable `pinterest__using_keywords` that allows users to disable the keywords reports within Pinterest if they are not needed or are not located within the users source schema.

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [X] dbt compile
- [X] dbt run –full-refresh
- [X] dbt run
- [X] dbt test
- [X] dbt run –vars (pinterest__using_keywords set to both true and false)

Before marking this PR as "ready for review" the following have been applied:
- [X] The appropriate issue has been linked and tagged
- [X] You are assigned to the corresponding issue and this PR
- [ ] BuildKite integration tests are passing

### Detailed Validation
Please acknowledge that the following validation checks have been performed prior to marking this PR as "ready for review":
- [X] You have validated these changes and assure this PR will address the respective Issue/Feature.
- [X] You are reasonably confident these changes will not impact any other components of this package or any dependent packages.
- [X] You have provided details below around the validation steps performed to gain confidence in these changes.

- Variable set to `false` with all other ad platforms (excluding amazon ads) enabled.
  - The keyword tables are not included 
![image](https://github.com/fivetran/dbt_ad_reporting/assets/74217849/29bbc5f9-5c6f-417a-9f5e-f97e297a5171)

- Variable set to `true` with all other ad platforms (excluding amazon ads) enabled.
  - The keyword tables are included
![image](https://github.com/fivetran/dbt_ad_reporting/assets/74217849/8c038ead-810c-46d0-85b2-134f80d32146)

- Variable not defined (default) with all other ad platforms (excluding amazon ads) enabled.
  - The keyword tables are included
![image](https://github.com/fivetran/dbt_ad_reporting/assets/74217849/b09c2848-baee-47f6-bb35-ef354a725d57)

### Standard Updates
Please acknowledge that your PR contains the following standard updates:
- Package versioning has been appropriately indexed in the following locations:
    - [X] indexed within dbt_project.yml
    - [X] indexed within integration_tests/dbt_project.yml
- [X] CHANGELOG has individual entries for each respective change in this PR
    
- [X] README updates have been applied (if applicable)
    
- [n/a] DECISIONLOG updates have been updated (if applicable)
- [n/a] Appropriate yml documentation has been added (if applicable)

### dbt Docs
Please acknowledge that after the above were all completed the below were applied to your branch:
- [X] docs were regenerated (unless this PR does not include any code or yml updates)

### If you had to summarize this PR in an emoji, which would it be?
 
📚

2023-06-07 22:07 UTC, fivetran-reneeli requested changes
Changes look good but don't forget to update the version!

2023-06-08 19:16 UTC, fivetran-joemarkiewicz commented
> Changes look good but don't forget to update the version!

Thanks for catching @fivetran-reneeli, this is going to be merged into the release/v1.4.0 branch so the version should be bumped when merging into there. If all else looks good would you be able to approve or add any other comments before merging to the release branch. Thanks!

2023-06-08 19:38 UTC, fivetran-reneeli commented
Looks good!

2023-06-08 19:38 UTC, fivetran-reneeli approved these changes
Lgtm!

2023-06-08 19:41 UTC, merged

2023-06-09 16:11 UTC, fivetran-catfritz commented on packages.yml
Standard reminder.